import os
import sys
import json
import wandb
import shutil
import argparse
import litellm

import dataset.dataset as dataset

def get_combined_ids():
    with open("combined_ids.txt", "r") as f:
        return f.read().splitlines()

def get_generated_codes():
    combined_ids = get_combined_ids()
    runs = ["r1", "r2", "r3", "r4", "r5"]
    codes = {}

    directory = os.path.join("generated_code")
    print("Getting generated codes...")
    for file in os.listdir(directory):
        # if model_engine in file:
        with open(os.path.join(directory, file), "r") as f:
            code = f.read()
        
        for combined_id in combined_ids:
            for run in runs:
                if combined_id in file and run in file:
                    if combined_id not in codes:
                        codes[combined_id] = {}
                    codes[combined_id][run] = code
    return codes


def verify_code(model_engine):
    codes = get_generated_codes()
    for combined_id, runs in codes.items():
        print("-" * 100)
        print(f"Verifying {combined_id}")
        print(f"Runs: {runs.keys()}")

        metadata = dataset.get_datapoint(combined_id, only_metadata=True)
        func_details = metadata["func_details"][0]

        prompt = f"You are an expert software engineer. You are given various code snippets that are generated by an LLM that implement function {func_details['name']} according to {func_details['description']}. Your job is to verify the correctness of the code and pick the best candidate. Here are the code snippets: "

        for run, code in runs.items():
            prompt += f"Code {run}: {code}\n\n"
        
        prompt += "Please pick the best candidate and return the name of the code snippet. Explain your reasoning."

        response = litellm.completion(
            model=model_engine,
            messages=[{"role": "user", "content": prompt}],
        )

        print(f"Response: {response.choices[0].message.content}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--model-engine", type=str, required=True)
    args = parser.parse_args()

    verify_code(args.model_engine)
