command:
- bash
- run_curtail_from_env.sh
- ${args}
method: grid
parameters:
  subtests:
    curtail:
      combined-id:
        - '2303.11932_2'
        - '2303.11932_14'
        - '2303.11932_10'
        - '2303.11932_12'
        - '2303.11932_6'

