command:
- bash
- run_exp_from_env.sh
- ${args}
method: grid
parameters:
  model-engine: gpt-4o-mini # change these as needed
  agent: 'ReAct'
  memory: 'Full'
  retrieval: 'full' # optional
  code-retrieval: 'full' # optional
  subtests:
    test:
      combined-id:
        - '0000.00000_0'
        # add more combined-ids as needed
