command:
- bash
- run_exp_from_env.sh
- ${args}
method: grid
parameters:
  agent: ReAct 
  memory: Full
  subtests:
    n_4:
      combined-id:
        # sample from experiments_4.yml
      model-engine: 
        - 'gpt-4o'
        - 'gpt-4o-mini'
        - 'anthropic/claude-3-5-sonnet-20240620'
        - 'anthropic/claude-3-7-sonnet-20250219'