command:
- bash
- run_exp_from_env.sh
- ${args}
method: grid
parameters:
  model-engine: gpt-4o
  agent: 'ReAct'
  memory: 'Full'
  environment: 'MLAgentBench'
  retrieval: 'oracle'
  code-retrieval: 'agent'
  subtests:
    oracle_retrieval_prompting_1:
      combined-id:
        - "2205.00048_0"
        - "2205.00048_1"
        - "2205.00048_2"
        - "2205.00048_3"
        - "2205.00048_4"
        - "2205.00048_5"
