command:
- bash
- run_exp_from_env.sh
- ${args}
method: grid
parameters:
  model-engine: gpt-4o-mini
  agent: refsol
  memory: Summary
  environment: MLAgentBench
  subtests:
    agent_architecture:
      combined-id:
        - '2303.11932_'
        - '2309.05569_'
        - '2110.03485_'
        - '2205.00048_'
                