command:
- bash
- run_exp_from_env.sh
- ${args}
method: grid
parameters:
  model-engine: gpt-4o-mini
  agent: Planning 
  memory: Summary
  environment: MLAgentBench
  subtests:
    agent_architecture:
      combined-id:
        - '2303.11932_0'
        - '2309.05569_0'
        - '2110.03485_0'
        - '2205.00048_0'
                