command:
- bash
- run_exp_from_env.sh
- ${args}
method: grid
parameters:
  _tags:
    value: oracle_retrieval_prompting_1
  agent:
    value: ReAct
  code-retrieval:
    value: agent
  combined-id:
    values:
    - '2205.00048_0'
    - '2205.00048_1'
    - '2205.00048_2'
    - '2205.00048_3'
    - '2205.00048_4'
    - '2205.00048_5'
  environment:
    value: MLAgentBench
  memory:
    value: Full
  model-engine:
    value: gpt-4o
  retrieval:
    value: oracle
