rm -rf workspace/FC
rm -rf */__pycache__
rm -rf */*/__pycache__
rm -rf */*/*/__pycache__
rm -rf */*/*/*/__pycache__
rm -rf agents/MLAgentBench/MLAgentBench/workspace
rm -rf agents/MLAgentBench/MLAgentBench/logs
rm -rf agents/MLAgentBench/MLAgentBench/benchmarks/*
rm -rf agents/AutoAgent/workspace/*
rm -rf dataset/refsols/*
rm -rf wandb
