import os
import json
import csv
import shutil
from litellm import completion, completion_cost
import sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from autoexperiment.dataset.dataset import get_datapoint

class LLMResponse:
    def __init__(self, prompt, response, prompt_tokens, completion_tokens, cost, error) -> None:
        self.prompt = prompt
        self.response = response
        self.prompt_tokens = prompt_tokens
        self.completion_tokens = completion_tokens
        self.cost = cost
        self.error = error

this_dir = os.path.dirname(__file__)

def percent_loss(gold, pred):
    return abs(gold - pred) / gold

def collect_loss(gold, pred, metric_fn=percent_loss):
    loss = []
    if isinstance(pred, str):
        try:
            pred = json.loads(pred)
        except Exception as e:
            try:
                pred = int(pred)
            except Exception as e:
                # print(f"Error in converting prediction: {pred}")
                return [1]

    if isinstance(pred, dict):
        for key in gold:
            if key not in pred:
                pred[key] = 0.0
            loss += collect_loss(gold[key], pred[key], metric_fn)
    elif isinstance(pred, list):
        for i in range(len(pred)):
            loss += collect_loss(gold[i], pred[i], metric_fn)
    else:
        loss += [metric_fn(gold, pred)]
    return loss


def calculate_loss(gold, pred, metric_fn=percent_loss):
    if isinstance(pred, str):
        pred = json.loads(pred)

    loss_per_exp = {}
    correct_per_exp = {}
    correct_count = 0
    all_correct = True
    
    for key in gold:
        if key in pred:
            losses = collect_loss(gold[key], pred[key], metric_fn)
            loss = sum(losses) / len(losses)
        else:
            loss = 1
        loss_per_exp[key] = loss
        correct = loss <= 0.05
        if correct:
            correct_count += 1 
        correct_per_exp[key] = correct
        all_correct = all_correct and correct
    return loss_per_exp, correct_per_exp, correct_count, all_correct
 

def get_gold_output_and_code(combined_id):
    X, y, metadata = get_datapoint(combined_id=combined_id)
    func = X["funcs_to_block"][0]
    gold_code = func["gold_standard_code"]
    gold_context = func["relevant_paper"]
    shutil.rmtree(X["path"])
    return gold_code, y, gold_context
    
def call_llm(messages, model, **kwargs):
    try:
        response = completion(model=model, messages=messages)
        cost = completion_cost(completion_response=response, model=model, messages=messages)
        return LLMResponse(prompt=messages,
                        response=response.choices[0].message, 
                        prompt_tokens=response.usage.prompt_tokens, 
                        completion_tokens=response.usage.completion_tokens, 
                        cost=cost,
                        error=False)
    except Exception as e:
        message = f"Error calling llm {model}: {e}"
        print(message)
        return LLMResponse(prompt=messages, response=message, prompt_tokens=0, completion_tokens=0, cost=0, error=True)


def extract_generated_code(contents, gold_code, model):
    # extract all the diffs
    diffs = contents.split("+++")[1:]
    diffs = [diff.split("######################################")[0] for diff in diffs]
    if len(diffs) == 0:
        print("No diff found. Using last write_file contents")
        generated_code = contents.split("name='write_file'")[-2].split('"content": ')[-1][1:-4]
        return generated_code

        # code = contents.split("```python")[-1].split("```")[0]
        # return code
    diffs = '\n'.join(diffs)
    header = gold_code.split('\n')[0]

    prompt = f"Given the following sequence of diffs that try to implement a single Python function, write the current state of this function. Function header: {header} Diffs: {diffs}. Give your answer in markdown format with ```python."

    response = call_llm([{"role": "user", "content": prompt}], model)
    generated_code = response.response.content
    if "```python" in generated_code:
        generated_code = generated_code.split("```python")[1].split("```")[0]
    print("#" * 10 + " GENERATED CODE " + "#"*10)
    print(generated_code)
    print("#" * 10 + " GOLD CODE " + "#"*10)
    print(gold_code)
    return generated_code

def run_analysis(generated_code, gold_code, model):
    # compare 
    prompt = f"""I have a code snippet generated by a coding AI agent and the oracle code that it is trying to generate. The agent-generated code runs but produces an incorrect result. Explain why the agent code does not work.

### Generated Code
{generated_code}

### Oracle Code
{gold_code}
"""
    
    response = call_llm([{"role": "user", "content": prompt}], model)
    print("#" * 10 + " ANALYSIS " + "#"*10)
    print(response.response.content)
    print("#" * 30)
    return response.response.content


def classify(log_dir, setting): 
    for filename in os.listdir(log_dir):
        filepath = os.path.join(log_dir, filename)
        if not os.path.isfile(filepath):
            continue
            
        print(f"Processing {filename}")

        try:
            # TODO: change this
            combined_id = "_".join(filename.split("retrieval_")[1].split("_")[0:2])

            with open(filepath, 'r') as f:
                contents = f.read()

            # setting = "full"

            # if "Relevant text from research paper" in contents:
            #     setting = "oracle"
            # else:
            #     continue

            final_answer = contents.split("Observation:\n")[-1].split("\n")[0]
            print(f"Final answer: {final_answer}")
            final_answer = json.loads(final_answer)

            gold_code, gold_output, gold_context = get_gold_output_and_code(combined_id)

            loss_per_exp, correct_per_exp, correct_count, all_correct = calculate_loss(gold_output, final_answer)
            if any([loss != 0.0 and loss != 1.0 for loss in loss_per_exp.values()]) and not all_correct:
                incorrect_dir = os.path.join("agents", "traces", setting, "incorrect")
                shutil.copy(filepath, os.path.join(incorrect_dir, filename))
            elif all_correct:
                correct_dir = os.path.join("agents", "traces", setting, "correct")
                shutil.copy(filepath, os.path.join(correct_dir, filename))
            else:
                pass
                # failed_dir = os.path.join("agents", "traces", setting, "failed")
                # shutil.copy(filepath, os.path.join(failed_dir, filename))

        except Exception as e:
            # Copy failed file to traces directory
            print(e)
            # failed_dir = os.path.join("agents", "traces", setting, "failed")
            # shutil.copy(filepath, os.path.join(failed_dir, filename))

def main_analysis(trace_dir, model):
    filepath = os.path.join(trace_dir, "analysis.csv")
    if os.path.exists(filepath):
        with open(filepath, 'r') as csvfile:
            reader = csv.DictReader(csvfile)
            results = list(reader)
    else:
        results = []
    
    # Walk through all files in directory
    for root, dirs, files in os.walk(trace_dir):
        for filename in files:
            tracepath = os.path.join(root, filename)
            print(f"Processing {filename}...")
            if len([res for res in results if res['filename'] == filename]) > 0: 
                print("Already analyzed")
                continue

            try:
                if "agent_architecture_" in filename:
                    combined_id = "_".join(filename.split("agent_architecture_")[1].split("_")[0:2])
                elif "main_" in filename:
                    combined_id = "_".join(filename.split("main_")[1][3:].split("_")[0:2])
                else:
                    combined_id = "_".join(filename.split("retrieval_")[1].split("_")[0:2])


                with open(tracepath,'r') as f:
                    contents = f.read()

                # final_answer = contents.split("Observation:\n")[-1].split("\n")[0]
                # final_answer = json.loads(final_answer)

                # gold_code, gold_output, gold_context = get_gold_output_and_code(combined_id)
                gold_code, gold_output, gold_context = "", "", ""

                generated_code = extract_generated_code(contents, gold_code, model)
                if "incorrect" in trace_dir:
                    analysis = run_analysis(generated_code, gold_code, model)
                else:
                    analysis = "Code is correct"

                results.append({"filename": filename, "combined_id": combined_id, "gold_code": gold_code, "generated_code": generated_code, "analysis": analysis, "gold_context": gold_context})

            except Exception as e:
                print(e)
                pass


    # Write results to CSV
    with open(filepath, 'w', newline='') as csvfile:
        fieldnames = ['filename', 'combined_id', 'gold_code', 'generated_code', 'analysis', 'gold_context']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        
        writer.writeheader()
        for result in results:
            writer.writerow(result)
 

if __name__=="__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", type=str, required=True)
    parser.add_argument("--log-dir", type=str, required=True)
    args = parser.parse_args()

    main_analysis(args.log_dir, args.model)