import os
import sys
import csv
import json
import wandb
import shutil
import argparse
import litellm

import sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import autoexperiment.dataset.dataset as dataset

def get_combined_ids():
    with open("combined_ids.txt", "r") as f:
        return f.read().splitlines()


def get_generated_codes(log_dir):
    combined_ids = get_combined_ids()
    runs = ["r1", "r2", "r3", "r4", "r5"]
    codes = {combined_id: {} for combined_id in combined_ids}

    print("Getting generated codes...")
    analysis_file = os.path.join(log_dir, "analysis.csv")
    with open(analysis_file, "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            combined_id = row["combined_id"]
            if combined_id not in combined_ids: continue
            for run in runs:
                if run in row["filename"]:
                    codes[combined_id][run] = row["generated_code"]
                    break

    return codes


def verify_code(log_dir, model_engine):
    codes = get_generated_codes(log_dir)
    results = {}
    for combined_id, runs in codes.items():
        print("-" * 100)
        print(f"Verifying {combined_id}")
        print(f"Runs: {runs.keys()}")

        metadata = dataset.get_datapoint(combined_id=combined_id, only_metadata=True)
        func_details = metadata["func_details"][0]

        prompt = f"You are an expert software engineer. You are given various code snippets that are generated by an LLM that implement function {func_details['name']} according to {func_details['description']}. Your job is to verify the correctness of the code and pick the best candidate. Here are the code snippets: "

        for run, code in runs.items():
            prompt += f"Code {run}: {code}\n\n"
        
        prompt += "Please pick the best candidate and return the name of the code snippet. Explain your reasoning."

        response = litellm.completion(
            model=model_engine,
            messages=[{"role": "user", "content": prompt}],
        )

        response = response.choices[0].message.content

        print(f"Response: {response}")
        results[combined_id] = response

    with open(os.path.join(log_dir, "results.json"), "w") as f:
        json.dump(results, f)

    return results


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--log-dir", type=str, required=True)
    parser.add_argument("--model-engine", type=str, required=True)
    args = parser.parse_args()

    verify_code(args.log_dir, args.model_engine)
