FROM anibali/pytorch:2.0.0-cuda11.8-ubuntu22.04

# Set up time zone.
ENV TZ=UTC
RUN sudo ln -snf /usr/share/zoneinfo/$TZ /etc/localtime

USER root
RUN apt-get update && apt-get install -y --no-install-recommends gcc &&  rm -r /var/lib/apt/lists/*

ARG env_name="myenv" 

# Copy MLAgentBench code and environment.yml 
WORKDIR /app/MLAgentBench
ADD ./baselines/MLAgentBench/ ./
WORKDIR /app
COPY ./baselines/openai_api_key.txt .

# Install experiment dependencies
COPY ./baselines/tmp/environment.yml .
RUN echo ${env_name}
RUN conda env create -f environment.yml
RUN conda rename -n ${env_name} myenv
SHELL ["conda", "run", "-n", "myenv", "/bin/bash", "-c"]

# Install MLAgentBench dependencies
RUN pip install tiktoken
RUN pip install anthropic
RUN pip install openai
RUN pip install langchain
RUN pip install dacite

# Run MLAgentBench as default command
ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "myenv", "python", "-u", "MLAgentBench/MLAgentBench/runner.py", "--task", "task", "--max-steps", "20", "--llm-name", "gpt-4-1106-preview", "--edit-script-llm-name", "gpt-4-1106-preview", "--fast-llm-name", "gpt-3.5-turbo-1106", "--log-dir", "MLAgentBench/logs", "--max-time", "72000", "--work-dir", "MLAgentBench/workspace"]
